[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "kernel"
# path = "src/main.rs"
# test = false
# doctest = false
# bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
aarch64.path = "arch/aarch64"

[workspace]
members = ["arch/aarch64", "bsp/rpi3"]
