[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
aarch64.path = "arch/aarch64"

[workspace]
members = ["arch/aarch64", "bsp/rpi3"]
