[build]
# TODO: Provide based on Arch
target = "aarch64-unknown-none-softfloat"

# TODO: Dynamically provide these based on the current BSP/Arch
rustflags = [
    # Search in `./bsp/rpi3` for files
    "-C",
    "link-arg=--library-path=./bsp/rpi3",
    # Use `kernel.ld` as the linker script
    "-C",
    "link-arg=--script=kernel.ld",
]

# Allow for a statically linked, free-standing binary to be natively compiled to all OSes
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]
